
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Vicente Junior", email = "vicente19981@live.com"},
]
dependencies = [
    "autopep8>=2.0.2",
]
requires-python = ">=3.10.2"
license = {text = "MIT"}
